#variables
@baseUrl = http://localhost:3333

# Heal check
GET {{baseUrl}}/health
# @name healthCheck

###

# Get rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# Create room
# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
    "name": "Sala de teste 2",
    "description": "Essa é uma sala de teste 2"
}

###
@roomId = {{createRoom.response.body.$.roomId}}
###

# Get room questions
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# Create question
# @name createQuestion
POST {{baseUrl}}/rooms/{{roomId}}/questions
Content-Type: application/json

{
    "question": "Qual o conceito de x dentro de y ?"
}